language: android
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-24
jdk:
- oraclejdk8
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_script: cd MissMe
script:
- adb devices
- "./gradlew assembleDebug"