language: android
notifications:
  email:
    recipients:
      - livinmathew99@gmail.com
    on_success: change
    on_failure: always
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools # Running this twice get's the latest build tools
  - platform-tools
  - android-27
  - build-tools-27.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-27
before_script: cd MissMe
script:
- adb devices
- "./gradlew assembleDebug"
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\8933bad161af4178b1185d1a37fbf41ea5269c55\d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"